---
settings:
  name: Azure Blob storage
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti sullo storage Azure Blob
    url: "/index.html"
  - title: Note di rilascio
    url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Visualizza i tuoi account di storage Azure Blob
      url: "/task-view-azure-blob-storage.html"
  - title: Gestire gli account di storage Azure Blob
    entries:
    - title: Aggiungere nuovi account storage
      url: "/task-add-blob-storage.html"
    - title: Modificare le impostazioni degli account di storage
      url: "/task-change-blob-storage-settings.html"
    - title: Utilizza i servizi dati NetApp con lo storage Azure Blob
      url: "/task-blob-enable-data-services.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
