---
settings:
  name: Azure Blob storage
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti sullo storage Azure Blob
    url: "/index.html"
  - title: Note di rilascio
    url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Visualizza i tuoi account di storage Azure Blob
      url: "/task-view-azure-blob-storage.html"
  - title: Gestire gli account di storage Azure Blob
    entries:
    - title: Aggiungere nuovi account storage
      url: "/task-add-blob-storage.html"
    - title: Modificare le impostazioni degli account di storage
      url: "/task-change-blob-storage-settings.html"
    - title: Utilizza i servizi dati NetApp con lo storage Azure Blob
      url: "/task-blob-enable-data-services.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Visualizza i tuoi account di storage Azure Blob
      url: task-view-azure-blob-storage.html
  - title: Gestire gli account di storage Azure Blob
    links:
    - title: Aggiungere account di storage Blob
      url: task-add-blob-storage.html
    - title: Modificare le impostazioni dell'account di storage
      url: task-change-blob-storage-settings.html
    - title: Utilizza i servizi dati NetApp con lo storage Azure Blob
      url: task-blob-enable-data-services.html
  - title: Ulteriori informazioni
    links:
    - title: Documentazione dello storage Azure Blob per la gestione al di fuori di
        BlueXP
      url: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction
  - title: Blog e community
    links:
    - title: Community NetApp
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://bluexp.netapp.com/blog/topic/cloud-manager
    - title: Webinar BlueXP
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Tutta la documentazione BlueXP
