---
sidebar: sidebar 
permalink: task-blob-enable-data-services.html 
keywords: blob storage, blob working environment, azure blob storage accounts, azure blob working environment 
summary: Dopo aver scoperto gli account di storage Azure Blob in BlueXP, è possibile utilizzare i servizi dati NetApp per il backup, il tiering e la sincronizzazione dei dati. 
---
= Utilizza i servizi dati NetApp con lo storage Azure Blob
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver scoperto gli account di storage Azure Blob in BlueXP, è possibile utilizzare i servizi dati NetApp per il backup, il tiering e la sincronizzazione dei dati.

* Utilizza *backup e ripristino BlueXP* per eseguire il backup dei dati dai sistemi ONTAP e Cloud Volumes ONTAP on-premise allo storage Azure Blob.
+
Per iniziare, accedi a Canvas e trascina un ambiente di lavoro ONTAP o Cloud Volumes ONTAP on-premise nell'ambiente di lavoro dello storage Azure Blob.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Scopri di più sul backup dei dati ONTAP nello storage Azure Blob"^].

* Utilizza il tiering * BlueXP per tiering dei dati inattivi dai cluster ONTAP on-premise allo storage Azure Blob.
+
Per iniziare, accedi a Canvas e trascina un ambiente di lavoro ONTAP on-premise nell'ambiente di lavoro dello storage Azure Blob.

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-azure.html["Scopri di più sul tiering dei dati ONTAP nello storage Azure Blob"^].

* Utilizzare *BlueXP copy and Sync* per sincronizzare i dati da o verso gli account di storage Azure Blob.
+
Per iniziare, accedi a Canvas e trascina l'ambiente di lavoro di origine nell'ambiente di lavoro di destinazione. Il tuo ambiente di lavoro Azure Blob Storage può essere l'origine o la destinazione.

+
È inoltre possibile selezionare l'ambiente di lavoro Azure Blob Storage e fare clic su *Copy & Sync* (Copia e sincronizza) dal pannello Services (servizi) per sincronizzare i dati con o da account di storage Azure Blob.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["Scopri di più sul servizio di copia e sincronizzazione BlueXP"^].


